---
title: "heatmap chip-exo"
author: "Fabian Blombach"
date: "26/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(rtracklayer)
require(ggplot2)
require(cowplot)

genomeFasta <- "../genome_data/SsoP2/NC_002754.fna"

#coordinates of CRISPR repeats
locus_A<-read.table("../genome_data/SsoP2/CRISPR_locus_A_repeatStart.bed")
locus_B<-read.table("../genome_data/SsoP2/CRISPR_locus_B_repeatStart.bed")


#Cbp1 ChIP-exo data filtered for 1st or 2nd read
fw.1st <- "../data/ChIP-exo_S.solfataricus/Cbp1_sso_gm.1stRead.plus.bw"
rv.1st <- "../data/ChIP-exo_S.solfataricus/Cbp1_sso_gm.1stRead.minus.bw"


fw.2nd <- "../data/ChIP-exo_S.solfataricus/Cbp1_sso_gm.2ndRead.plus.bw"
rv.2nd <- "../data/ChIP-exo_S.solfataricus/Cbp1_sso_gm.2ndRead.minus.bw"



Sys.setenv(fw.1st = fw.1st, rv.1st = rv.1st, fw.2nd = fw.2nd, rv.2nd = rv.2nd)
```

```{r coordinates}
coord_1 <- IRangesList("gi|15896971|ref|NC_002754.1|" = IRanges(locus_A$V3 -20, width=65))
coord_2 <- IRangesList("gi|15896971|ref|NC_002754.1|" = IRanges(locus_B$V3 -44, width=65))

```

```{r data import}
A.data.fw.1st <- import.bw(fw.1st, selection = coord_1, as="NumericList")
B.data.fw.1st <- import.bw(rv.1st, selection = coord_2, as="NumericList")
A.data.rv.1st <- import.bw(rv.1st, selection = coord_1, as="NumericList")
B.data.rv.1st <- import.bw(fw.1st, selection = coord_2, as="NumericList")

A.data.fw.2nd <- import.bw(fw.2nd, selection = coord_1, as="NumericList")
B.data.fw.2nd <- import.bw(rv.2nd, selection = coord_2, as="NumericList")
A.data.rv.2nd <- import.bw(rv.2nd, selection = coord_1, as="NumericList")
B.data.rv.2nd <- import.bw(fw.2nd, selection = coord_2, as="NumericList")
```

```{r into data.frame}
A.dataf.fw.1st <- data.frame(do.call(rbind, A.data.fw.1st@listData))
A.dataf.rv.1st <- data.frame(do.call(rbind, A.data.rv.1st@listData))
A.dataf.fw.2nd <- data.frame(do.call(rbind, A.data.fw.2nd@listData))
A.dataf.rv.2nd <- data.frame(do.call(rbind, A.data.rv.2nd@listData))

B.dataf.fw.1st <- data.frame(do.call(rbind, B.data.fw.1st@listData))
B.dataf.rv.1st <- data.frame(do.call(rbind, B.data.rv.1st@listData))
B.dataf.fw.2nd <- data.frame(do.call(rbind, B.data.fw.2nd@listData))
B.dataf.rv.2nd <- data.frame(do.call(rbind, B.data.rv.2nd@listData))


colnames(A.dataf.fw.1st)<- 1:65
colnames(A.dataf.rv.1st)<- 1:65
colnames(A.dataf.fw.2nd)<- 1:65
colnames(A.dataf.rv.2nd)<- 1:65

colnames(B.dataf.fw.1st)<- 65:1
colnames(B.dataf.rv.1st)<- 65:1
colnames(B.dataf.fw.2nd)<- 65:1
colnames(B.dataf.rv.2nd)<- 65:1

```

```{r combining the two loci}
data.fw.1st<-rbind(A.dataf.fw.1st, B.dataf.fw.1st)
data.rv.1st<-rbind(A.dataf.rv.1st, B.dataf.rv.1st)

data.fw.2nd<-rbind(A.dataf.fw.2nd, B.dataf.fw.2nd)
data.rv.2nd<-rbind(A.dataf.rv.2nd, B.dataf.rv.2nd)
```

```{r calculating mean}

mean.fw.1st <- apply(data.fw.1st, 2, mean)
mean.rv.1st <- apply(data.rv.1st, 2, mean)

mean.fw.2nd <- apply(data.fw.2nd, 2, mean)
mean.rv.2nd <- apply(data.rv.2nd, 2, mean)

comb.data<-data.frame(fw.1st=mean.fw.1st, rv.1st=mean.rv.1st, fw.2nd=mean.fw.2nd, rv.2nd=mean.rv.2nd)
```

```{r plotting}
theme_chip<- function (base_size = 11, base_family = "") 
{
  theme_bw(base_size = base_size, base_family = base_family) %+replace% 
    theme(panel.background = element_blank(), 
          panel.border = element_blank(), 
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(), 
          axis.title.x=element_blank(), 
          axis.text.x=element_blank(), 
          axis.ticks.x=element_blank(),
          axis.title.y=element_blank(), 
          plot.margin = unit(c(1,1,0,1), "mm"), complete = TRUE)
}

#setting y-axis limits depending on which CRISPR arrays plotted
lm <- 1200


g <- ggplot(data=comb.data) + 
  geom_area(aes(x=1:65, y=fw.1st),  fill="#0000ffff", alpha=0.5) + 
  geom_line(aes(x=1:65, y=fw.1st),  colour="#0000ffff") +
  geom_area(aes(x=1:65, y= -fw.2nd),  fill="#000092ff", alpha=0.5) + 
  geom_line(aes(x=1:65, y= -fw.2nd),  colour="#000092ff") +
  theme_chip()  +
  theme(axis.line.x = element_blank(), axis.line.y = element_line(color="black", size = 0.5)) +
  scale_y_continuous(breaks = c(-lm,lm), limits = c(-lm,lm), expand = c(0, 0), position="right") +
  scale_x_continuous(expand = c(0, 0), limits = c(1,65))
g

g2 <- ggplot(data=comb.data) + 
  geom_area(aes(x=1:65, y=rv.2nd),  fill="#0000ffff", alpha=0.5) + 
  geom_line(aes(x=1:65, y=rv.2nd),  colour="#0000ffff") +
  geom_area(aes(x=1:65, y= -rv.1st),  fill="#000092ff", alpha=0.5) + 
  geom_line(aes(x=1:65, y= -rv.1st),  colour="#000092ff") +
  theme_chip()  +
  theme(axis.line.x = element_blank(), axis.line.y = element_line(color="black", size = 0.5)) +
  scale_y_continuous(breaks = c(-lm,lm), limits = c(-lm,lm), expand = c(0, 0), position="right") +
  scale_x_continuous(expand = c(0, 0), limits = c(1,65))
g2

p <- plot_grid(g, g2, ncol = 2, align="h")
p
save_plot(paste0("../plots/chip-exo.aggregate.CRISPR_AB.1stVs2ndRead.pdf"), p, base_width=6, base_height=3)

```


